version: '3.8'

services:
  react-app:
    build:
      context: ./react-client
      dockerfile: Dockerfile
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - app-network

  express-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server-app
    ports:
      - "5000:5000"
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge
